### ISSUE TITLE
aye bruh why u take my readme icons :sob:

### ISSUE THREAD

**Issue by dread-pirate-robert** [NotClynt/NotClynt#2]

**Comment by NotClynt** [comment]
https://rahuldkjain.github.io/gh-profile-readme-generator/
+
https://lanyard-profile-readme.vercel.app

**Comment by dread-pirate-robert** [comment]
thats what i use lmao u jus took it u didnt have any of that before lmao

**Comment by NotClynt** [comment]
> thats what i use lmao u jus took it u didnt have any of that before lmao

I didn't take any icons from you.
And your readme looks completely different the only thing our readmes have in common is the discord profile embed. And this one can be made by anyone

**Comment by NotClynt** [comment]
Just because you use these sites doesn't mean no one uses them anymore.
And do you really think that normal emojis are your "ICONS" right now?

**Comment by dread-pirate-robert** [comment]
lol
